name: Main build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Environment settings
        run: |
         DB_HOST=$GITHUB_ENV{DB_HOST}
         DB_NAME=$GITHUB_ENV{DB_NAME}
         DB_PASS=$GITHUB_ENV{DB_PASS}
         DB_USER=$GITHUB_ENV{DB_USER}
         export DB_HOST
         export DB_NAME
         export DB_PASS
         export DB_USER
      - name: PHPUnit tests
        run: composer run-script test
