name: Main build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: NeptuniumEnv

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: sudo composer install --prefer-dist --no-progress

  tests:
    runs-on: ubuntu-latest
    environment: NeptuniumEnv

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6

      - name: Create .env file
        env:
          NEP_DB_HOST: ${{ vars.DB_HOST }}
          NEP_DB_NAME: ${{ vars.DB_NAME }}
          NEP_DB_USER: ${{ vars.DB_USER }}
          NEP_DB_PASS: ${{ vars.DB_PASS }}
          NEP_BASE_URL: ${{ vars.NEP_BASE_URL }}
        run: |
          echo "NEP_DB_HOST=$NEP_DB_HOST"
          echo "NEP_DB_NAME=$NEP_DB_NAME"
          echo "NEP_DB_USER=$NEP_DB_USER"
          echo "NEP_DB_PASS=$NEP_DB_PASS"
          echo "NEP_BASE_URL=$NEP_BASE_URL"
          touch .env
          echo NEP_DB_HOST="$NEP_DB_HOST">> .env
          echo NEP_DB_NAME="$NEP_DB_NAME">> .env
          echo NEP_DB_USER="$NEP_DB_USER">> .env
          echo NEP_DB_PASS="$NEP_DB_PASS">> .env
          echo NEP_BASE_URL="NEP_BASE_URL">> .env
        shell: bash

      - name: PHPUnit tests
        run: |
          composer run-script test

        
